### ISSUE TITLE
cp: baserom.us.z64 no such file or directory

### ISSUE THREAD

**Issue by halpz** [EmeraldLoc/sm_osx#1]
getting cp: baserom.us.z64 no such file or directory even with the file in ~/Downloads

also says:

gcp cannot stat 'sm64ex/build/us_pc/' no such file or directory

**Comment by halpz** [comment]
not sure if there is a permissions missing or if i have to sign the app or something?

**Comment by halpz** [comment]
also my homebrew directory is /opt/homebrew/bin/brew rather than usr/local/bin/brew , so that install dependencies thing doesnt work

**Comment by halpz** [comment]
have you built this for intel rather than M1? because gcc@9 is for x86, not arm64

**Comment by EmeraldLoc** [comment]
Remember to put baser.us.z64 in the downloads folder

**Comment by EmeraldLoc** [comment]
Ok, so if you are trying to build ex-coop, run terminal via Rosetta 2 and then install brew at brew.sh. definitely gonna make this more clear in next update

**Comment by EmeraldLoc** [comment]
As for `cp: baserom.us.z64 no such file or directory` it shouldn't matter, check SM64Repos and see if baserom.us.z64 is there, if it is, then this error does not matter.

**Comment by halpz** [comment]
This was for render96

The actual make file for render96 has the wrong homebrew path for m1 macs anyway so it will not work, you need to change the /usr/local to opt/homebrew for it to work

**Comment by EmeraldLoc** [comment]
Hmm, ok one sec, let me see

**Comment by EmeraldLoc** [comment]
In the mean time, get intel ver of homebrew

**Comment by EmeraldLoc** [comment]
"also my homebrew directory is /opt/homebrew/bin/brew rather than usr/local/bin/brew" It runs both brew and usr/local/bin/brew. /usr/local/bin/brew is intel, once again, need to make It clear you should get the intel ver of homebrew., I should probably be checking if the user is running under rosetta or not swell.

**Comment by EmeraldLoc** [comment]
"The actual make file for render96 has the wrong homebrew path for m1 Macs anyway" I use a fork of render96ex by me to make it compile, you can see most of my forks here: https://github.com/EmeraldLoc/sm64ex

**Comment by EmeraldLoc** [comment]
Just compiled fine for me. Make sure you have an internet connection

**Comment by EmeraldLoc** [comment]
Did you figure it out? Need to know because I want to close this issue if you did

**Comment by EmeraldLoc** [comment]
Closing cuz no response
