### ISSUE TITLE
Render96 fails to complile due to audiofile error

### ISSUE THREAD

**Issue by jamiet83** [EmeraldLoc/sm_osx#11]
Hello, full log attached but this seems to be where the error is.

/usr/local/Cellar/gcc/12.2.0/include/c++/12/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
audiofile.cpp:3930:35: warning: 'template<class _Arg, class _Result> struct std::unary_function' is deprecated [-Wdeprecated-declarations]
 3930 | struct floatToFloat : public std::unary_function<Arg, Result>
      |                                   ^~~~~~~~~~~~~~
/usr/local/Cellar/gcc/12.2.0/include/c++/12/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
ld: warning: option -s is obsolete and being ignored
gcc-12 -I/opt/homebrew/include -I../include -I. -Wall -Wextra -Wno-unused-parameter -Wno-error=implicit-function-declaration -pedantic -std=c99 -O2 -s -Iaudiofile -Wno-uninitialized sdk-tools/tabledesign/codebook.c sdk-tools/tabledesign/estimate.c sdk-tools/tabledesign/print.c sdk-tools/tabledesign/tabledesign.c -o tabledesign -lm -Laudiofile -laudiofile -lstdc++ -lm
ld: warning: option -s is obsolete and being ignored
ld: library not found for -laudiofile
collect2: error: ld returned 1 exit status
gmake[1]: *** [Makefile:47: tabledesign] Error 1
gmake[1]: *** Waiting for unfinished jobs....
ar rcs libaudiofile.a audiofile.o
gmake[2]: Leaving directory '/Users/jamie/SM64Repos/render96ex/tools/audiofile'
gmake[1]: Leaving directory '/Users/jamie/SM64Repos/render96ex/tools'
Makefile:211: *** Failed to build tools.  Stop.
Finished Doin Stonks
[render96.txt](https://github.com/EmeraldLoc/sm_osx/files/10002747/render96.txt)

**Comment by jamiet83** [comment]
jamie@jamies-iMac ~ % brew install audiofile        
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

Warning: audiofile 0.3.6_1 is already installed and up-to-date.
To reinstall 0.3.6_1, run:
  brew reinstall audiofile
jamie@jamies-iMac ~ % 

I already have audiofile installed.

**Comment by EmeraldLoc** [comment]
Intel or Arm?

**Comment by jamiet83** [comment]
IntelOn 18 Nov 2022, at 22:30, Emerald Lockdown ***@***.***> wrote:﻿
Intel or Arm?

**Comment by EmeraldLoc** [comment]
Assuming you said intel, looks weird on my screen. Open up the terminal and run `which brew` and tell me the output

**Comment by jamiet83** [comment]
jamie@jamies-iMac ~ % which brew
/usr/local/bin/brew

**Comment by EmeraldLoc** [comment]
Try now

**Comment by jamiet83** [comment]
still fails sorry

ld: warning: option -s is obsolete and being ignored
gcc-12 -I/opt/homebrew/include -I../include -I. -Wall -Wextra -Wno-unused-parameter -Wno-error=implicit-function-declaration -pedantic -std=c99 -O2 -s -Iaudiofile -Wno-uninitialized sdk-tools/tabledesign/codebook.c sdk-tools/tabledesign/estimate.c sdk-tools/tabledesign/print.c sdk-tools/tabledesign/tabledesign.c -o tabledesign -lm -Laudiofile -laudiofile -lstdc++ -lm
ld: warning: option -s is obsolete and being ignored
ld: library not found for -laudiofile
collect2: error: ld returned 1 exit status
gmake[1]: *** [Makefile:47: tabledesign] Error 1
gmake[1]: *** Waiting for unfinished jobs....
ar rcs libaudiofile.a audiofile.o
gmake[2]: Leaving directory '/Users/jamie/SM64Repos/render96ex/tools/audiofile'
gmake[1]: Leaving directory '/Users/jamie/SM64Repos/render96ex/tools'
Makefile:211: *** Failed to build tools.  Stop.
Finished Doin Stonks

**Comment by EmeraldLoc** [comment]
should be fixed, if you could test it that would be great.

**Comment by EmeraldLoc** [comment]
Going to close this due to inactivity

**Comment by jamiet83** [comment]
Sorry for long delay, works as expected nowMany thanksOn 5 Mar 2023, at 01:14, Emerald Lockdown ***@***.***> wrote:﻿
should be fixed, if you could test it that would be great.
