### ISSUE TITLE
I have both Intel and Arm brew but sm_osx says I don't

### ISSUE THREAD

**Issue by MerBudd** [EmeraldLoc/sm_osx#13]
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/82082386/215801344-9a76eced-eae1-4dcc-8fef-836335e5af12.png">

I have tried deleting and reinstalling both, but the program still won't work. I've also put the program in many seperate directories, and even tried reinstalling **_it_** once.

By the way, seperate issue, the "Add new repo" button is grayed out. I don't know if it's related, but still.

Does anybody know how I can fix these?
Any help will be appreciated - thanks!

**Comment by EmeraldLoc** [comment]
Run brew --prefix for both the intel and arm version of homebrew. Make sure its on the same drive. The Arm one should be /opt/homebrew and the intel one should be /usr/local, I have not implemented it finding custom prefix's.

**Comment by EmeraldLoc** [comment]
Gonna close this because there is not enough information.
