### ISSUE TITLE
Cannot add new repo

### ISSUE THREAD

**Issue by Kurtjwest** [EmeraldLoc/sm_osx#14]
When choosing add new repo in the new update, nothing happens.
I am on macOS 13.2.1 arm64
I should mention that the previous version allowed me to add a repo but would fail to compile so going back a version will not work for me.

**Comment by EmeraldLoc** [comment]
Do you have homebrew installed? Try adding a repo thru the menu bar, ill do some testing myself.

**Comment by EmeraldLoc** [comment]
Well that was fast, I see the issue. When you have no repos, the Add New Repo button does not work, will make a hotfix.

**Comment by EmeraldLoc** [comment]
Try updating, it should be fixed now.

**Comment by Kurtjwest** [comment]
Works perfectly, thanks for the quick fix.
