### ISSUE TITLE
Termination Status 4 | sm64ex_coop beta 32.0.2

### ISSUE THREAD

**Issue by SamDS2109** [EmeraldLoc/sm_osx#19]
I don't know if this is related in anyway to the launcher or if it's on the games side but I cannot get the game to launch and even after several recompiles I keep getting the error "A Crash has happend. Termination Status: 4"

Macbook Pro, M1 Pro
macOS Ventura 13.2.1
sm_osx 1.2.9

Any help is appreciated, thanks!

**Comment by EmeraldLoc** [comment]
Uh oh, thats unexpected, let me look into it.

**Comment by EmeraldLoc** [comment]
Its on the development team, i'll look into it a lil more

**Comment by EmeraldLoc** [comment]
Go to the development team, something messed it up, because the development version compiles and works perfectly fine, sorry! I'll leave this open until it gets fixed

**Comment by EmeraldLoc** [comment]
Figured I'd throw it here as well, with debug enabled, it does not compile due to discord logging.

**Comment by SamDS2109** [comment]
Thanks for the fast reply! I'll be sure to wait for the solution.

**Comment by EmeraldLoc** [comment]
Hey, it should be fixed now, could you try it? If it works, then close this issue. I'll be closing this in 2-3 days
