### ISSUE TITLE
sm64ex hangs at patching and render96ex does not download

### ISSUE THREAD

**Issue by awsomenes** [EmeraldLoc/sm_osx#2]
Two encounters I am encountering.
1. When building sm64ex, it hangs at the patching part for a while.
2. render96ex repo appears to not download

**Comment by EmeraldLoc** [comment]
Does sm64ex build, and also, make sure you have logs enabled and send me the logs. Make sure you have homebrew. An update is releasing in like 1 minute so when the update is out open up sm_osx and download the update, it fixed many bugs, so it might fix yours.

**Comment by awsomenes** [comment]
Just downloaded new update, any button pressed crashes the app

**Comment by awsomenes** [comment]
Here is my report from the app crashing, removing SM64Repos did not accomplish anything
[log.txt](https://github.com/EmeraldLoc/sm_osx/files/8577541/log.txt)

**Comment by EmeraldLoc** [comment]
Very interesting, go and delete sm_osx, then go to ~/Library/Application\ /Support/ and delete sm_osx, then download the latest version and try again

**Comment by awsomenes** [comment]
same exact issue

**Comment by EmeraldLoc** [comment]
[sm_osx.zip](https://github.com/EmeraldLoc/sm_osx/files/8586846/sm_osx.zip)
Try using this binary ant tell me if it works, if so then it had to do with the ! symbol and force unwrapping

**Comment by EmeraldLoc** [comment]
Try the above one first, if that one does not work, then try this binary. 
[sm_osx.zip](https://github.com/EmeraldLoc/sm_osx/files/8586906/sm_osx.zip)

**Comment by awsomenes** [comment]
same thing for both

**Comment by EmeraldLoc** [comment]
[sm_osx.zip](https://github.com/EmeraldLoc/sm_osx/files/8586935/sm_osx.zip)
Try this one, and if it crashes, can you send me a log for it. Thanks!

**Comment by EmeraldLoc** [comment]
Also, I would delete the previous sm_osx apps and put the new one in the applications folder

**Comment by awsomenes** [comment]
even after deleting sm_osx and SM64repos, every build after the first fails to start the game

**Comment by EmeraldLoc** [comment]
First: Hit the Install Dependencies button, second, it should say the game crashed, if you can send a screenshot or something like that over of the log, that would be great

**Comment by EmeraldLoc** [comment]
It's been 2 days, if I do not get a comment tomorrow, I will close this issue and consider it resolved
