### ISSUE TITLE
monterey 12.5 crash on install dependencies

### ISSUE THREAD

**Issue by beyondmeat** [EmeraldLoc/sm_osx#3]
Using 1.2.3

I have homebrew and python3 already installed. It crashes as soon as I click the install sm64 dependencies button.

Dug into the code and found the dependencies:
`brew install gcc gcc@9 sdl2 pkg-config glew glfw3 libusb audiofile coreutils`
Ran that fine.

The crash report was reported to apple.

**Comment by EmeraldLoc** [comment]
Fixed in #9
