### ISSUE TITLE
12.5 compiles sm64ex fine but UI does not add it to laucher, no way to launch game

### ISSUE THREAD

**Issue by beyondmeat** [EmeraldLoc/sm_osx#4]

**Comment by EmeraldLoc** [comment]
Make sure you have the option enabled before compilation. Also, the repos are stored in your home folder, then SM64Repos, so you can hit the `Add existing repo` button, and add the launcher manually

**Comment by EmeraldLoc** [comment]
Weird, just reproduced the bug, will look into it

**Comment by EmeraldLoc** [comment]
I have fixed this bug, and most of your other issues, so yay! Will release a new version

**Comment by EmeraldLoc** [comment]
Fixed in version 1.2.4
