### ISSUE TITLE
failed to compile sm64ex-alo

### ISSUE THREAD

**Issue by beyondmeat** [EmeraldLoc/sm_osx#6]
QoL patches, better camera, no draw distance, 60fps

```
Assembling: sound/sound_data.s -> build/us_pc/sound/sound_data.o
Undefined symbols for architecture x86_64:
  "_tree_seg3_dl_snowy_pine", referenced from:
      _snow_tree_geo in common1_geo.o
     (maybe you meant: _tree_seg3_dl_snowy_pine_transparent)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
gmake: *** [Makefile:1795: build/us_pc/sm64.us.f3dex2e] Error 1
```

**Comment by EmeraldLoc** [comment]
Hmm, thought I fixed that, will look into it

**Comment by EmeraldLoc** [comment]
Will leave this open until it is fully fixed

**Comment by beyondmeat** [comment]
@EmeraldLoc I submitted a PR to your -alo fork to fix it. basically just reverting the fix commit you did back in june fixes it lol.

**Comment by EmeraldLoc** [comment]
@beyondmeat I may have fixed the issue, if you could double check that intel compiles, that would be great

**Comment by beyondmeat** [comment]
@EmeraldLoc works for intel mac.

**Comment by beyondmeat** [comment]
You should be able to pull the upstream changes and it works too (which I did on my fork)

**Comment by EmeraldLoc** [comment]
Cool, it works on arm now as well, will close this pr once v1.2.5 releases

**Comment by EmeraldLoc** [comment]
*Oh, and I merged your pr, however it did not compile on arm, so I needed to fix it*

**Comment by EmeraldLoc** [comment]
Actually, should close this now. As a temp fix, enable developer repos
